theme: jekyll-theme-cayman
title: Avoiding Side Effects in Complex Environments
description: Making agents behave with an unsupervised penalty term.
logo: /aup.png
repo_url: https://github.com/neale/safelife-k2
permalink: https://github.com/neale/safelife-k2
plugins:
  - 'jekyll-github-metadata'
